import 'mocha';
import * as chai from 'chai';
import {join} from "node:path";
import {cwd} from "node:process";
import {statSync} from "node:fs"
import {CreateDirectoryTransform,CreateDirectoryPayload} from '#project';


const should = chai.should();
const expect = chai.expect;

describe('dual-build tests', () => {
  describe('create-directory-transform test', () => {
    describe('create-directory-transform.test', () => {
      const payload: CreateDirectoryPayload = {
        directory: {
          name: 'test',
          directoryPath: join(cwd(), './out/create-directory-tranform.test'),
          autogenerated: true,
          transient: false
        },
        errorOnExists: false
      };
      it('should create a directory', async function () {
        const transform = new CreateDirectoryTransform(0);
        await transform.executeImplPayloadIn(undefined, payload);
        const stat = statSync(payload.directory.directoryPath);
        stat.isDirectory().should.be.true;
      });
    });
  });
})

